name: willbond
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  firebase_messaging:
  http: ^0.13.4      #use with network
#  progress_dialog: ^1.2.4 # use with dilog
  response: ^1.0.0
  shared_preferences: ^2.0.12
  
#  shared_preferences: ^0.5.8
  sqflite: ^2.0.2
  path_provider: ^2.0.8
  intl: ^0.17.0
#  flutter_local_notifications: ^2.0.0+1
  cached_network_image: ^3.2.0
#  meet_network_image: ^0.1.2
  image_picker: ^0.8.4+4
  persian_number_utility: ^1.1.1
  url_launcher: ^6.0.18


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true



  assets:
    - assets/
    - assets/logo.png
    - assets/we.png
    - assets/search.png
    - assets/imgperson.png
    - assets/r1.png
    - assets/r2.png
    - assets/r3.png
    - assets/new.png
    - assets/filter_icon.png
    - assets/icon_notif.png
    - assets/notif.png
    - assets/draftorder.png
    - assets/cart_empity.png
    - assets/noti_empity.png
    - assets/order.png
    - assets/no_wifi.png
    - assets/error.png
    - assets/iii.png
    - assets/double_ring_loading_io.gif


  fonts:
    - family: cairo
      fonts:
        - asset: fonts/cairo_regular.ttf
        - asset: fonts/cairo_semiBold.ttf
          style: normal
          weight: 400


